# LEVENSHTEIN DISTANCE
    This program calculates the levenshtein distance between two words
    The user is two type the two works, (seperated by space) and hit return (enter)
    

In [1]:
import numpy as np
words = input("Enter two words to find LD: ")
sp = words.split(" ")
splet1 = []
splet2 = []
for i in sp[0]:
    splet1.append(i)
for i in sp[1]:
    splet2.append(i)
m = len(splet1) + 1
n = len(splet2) + 1
A = np.zeros((m,n))
i = 0
for j in range(n):
    A[0,j] = i
    i += 1
i = 0
for j in range(m):
    A[j,0] = i
    i += 1
for i in range(1,m ):
    for j in range(1,n):
        if splet1[i - 1] == splet2[j - 1]:
             A[i,j] = min(A[i, j - 1], A[i - 1, j], A[i - 1, j - 1])
        else:
             A[i, j] = min(A[i, j - 1], A[i - 1, j], A[i - 1, j - 1]) + 1
print("LD: ",A[i,j])
print(A)
#print(clause1)
#print(clause2)

Enter two words to find LD: math hello
LD:  5.0
[[0. 1. 2. 3. 4. 5.]
 [1. 1. 2. 3. 4. 5.]
 [2. 2. 2. 3. 4. 5.]
 [3. 3. 3. 3. 4. 5.]
 [4. 3. 4. 4. 4. 5.]]
